name: Update LUG-Helper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  update-lughelper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Latest Tag
        id: get-tag
        continue-on-error: true
        run: |
          max_retries=5
          attempt=0
          success=false

          while [ $attempt -lt $max_retries ]; do
            echo "Attempt $((attempt+1)) to fetch tags..."
            latest_tag=$(curl -s --fail https://api.github.com/repos/starcitizen-lug/lug-helper/tags | jq -r '.[0].name') && success=true && break
            attempt=$((attempt+1))
            sleep 5
          done

          if [ "$success" = true ]; then
            sanitized_tag=$(echo "$latest_tag" | sed 's/^v//')
            echo "latest-tag=$sanitized_tag" >> $GITHUB_OUTPUT
          else
            echo "Failed to fetch latest tag after $max_retries attempts."
            echo "latest-tag=" >> $GITHUB_OUTPUT
          fi

      - name: Get Current Tag
        id: get-current-tag
        run: |
          current_tag=$(grep -oP '(?<=^%global tag ).*' lug-helper.spec)
          echo "current-tag=$current_tag" >> $GITHUB_OUTPUT

      - name: Compare Tags
        id: compare-tags
        run: |
          latest="${{ steps.get-tag.outputs.latest-tag }}"
          current="${{ steps.get-current-tag.outputs.current-tag }}"

          if [ -z "$latest" ]; then
            echo "No latest tag fetched. Assuming no update required."
            echo "new-tag=false" >> $GITHUB_OUTPUT
          elif [ "$latest" != "$current" ]; then
            echo "New tag available: $latest"
            echo "new-tag=true" >> $GITHUB_OUTPUT
          else
            echo "No update needed."
            echo "new-tag=false" >> $GITHUB_OUTPUT
          fi

      - name: Update Spec File
        if: ${{ steps.compare-tags.outputs.new-tag == 'true' }}
        run: |
          sed -i "s/%global tag .*/%global tag ${{ steps.get-tag.outputs.latest-tag }}/g" lug-helper.spec

      - name: Commit and Push Changes
        if: ${{ steps.compare-tags.outputs.new-tag == 'true' }}
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add lug-helper.spec
          git commit -m "lug-helper.spec: Update version to ${{ steps.get-tag.outputs.latest-tag }}"
          git push
